name: Bug Report
description: Report a bug
title: "[BUG]: "
labels: ["type:bug", "status:pending"]
body:
  # Summary message
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to contribute to this repository. Please fill out the form below to submit a new issue, and consider the following: 
        * Once you have submitted your new issue, the maintainer(s) will review the issue as soon as they have time available
        * This is a privately maintained repository, and as such issues may take longer than normal to resolve

  # Confirm that no similar issue exists
  - type: checkboxes
    id: new-issue-confirmation
    attributes:
      label: Have you checked for similar issues?
      description: Check existing issues to see if the problem you are experiencing has already been reported.
      options:
      - label: I have checked for similar issues
        required: true

  # Confirm that a title has been written
  - type: checkboxes
    id: title-confirmation
    attributes:
      label: Have you written an issue title?
      description: Write a title for the issue in the input field above. The title should describe the issue succinctly.
      options:
      - label: I have written an issue title
        required: true      


  # Package version dropdown
  - type: dropdown
    id: package-version
    attributes:
      label: Which version of this package are you using?
      description: |
        Select which version of this package you are using considering the following:
        * If you are experiencing an issue with multiple versions, select all appropriate versions
        * If you are using a local build, select "LOCAL", and specify the commit used to build the package in the "Additional Information" textarea
        * If the package version you are using is not listed, select "OTHER", and specify correct version in the "Additional Information" textarea
      multiple: true
      options:
        - v0.0.1
        - LOCAL (specify in "Additional Information")
        - OTHER (specify in "Additional Information")
    validations:
      required: true

  # Node LTS version dropdown
  - type: dropdown
    id: node-version
    attributes:
      label: Which version of NodeJS are you using?
      description: |
        Select which version of NodeJS you are using considering the following:
        * If you are experiencing an issue with multiple versions, select all appropriate versions
        * If you are not running this package using NodeJS, select "NOT APPLICABLE"
        * If you are not using an LTS version of NodeJS, select "OTHER", and specify the exact version in the "Additional Information" textarea
      multiple: true
      options:
        - v18.17.1 ~ Hydrogen
        - v16.20.2 ~ Gallium
        - v14.21.3 ~ Fermium
        - v12.22.12 ~ Erbium
        - v10.24.1 ~ Dubnium
        - v8.17.0 ~ Carbon
        - v6.17.1 ~ Boron
        - v4.9.1 ~ Argon
        - NOT APPLICABLE
        - OTHER (specify in "Additional Information")
    validations:
      required: true

  # Browser dropdown
  - type: dropdown
    id: browser
    attributes:
      label: Which browser are you using?
      description: |
        Select which browser you are using considering the following:
        * If you are experiencing an issue with multiple browsers, select all appropriate browsers
        * If you are not running this package in a browser, select "NOT APPLICABLE"
        * If the browser you are using is not listed, select "OTHER", and specify the browser in the "Additional Information" textarea
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Opera
        - Edge
        - NOT APPLICABLE
        - OTHER (specify in "Additional Information")
    validations:
      required: true

  # Issue description
  - type: textarea
    id: issue-description
    attributes:
      label: What issue did you encounter?
      description: |
        Tell us what bug you encountered and what should have happened
    validations:
      required: true

  # Reproduction steps
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can you reproduce this issue?
      description: |
        Tell us what bug you encountered and what should have happened
    validations:
      required: true

  # Additional information
  - type: textarea
    id: additional-information
    attributes:
      label: What additional information is available?
      description: |
        Tell us what bug you encountered and what should have happened
    validations:
      required: true