name: Bug Report
description: Report a bug
title: "[BUG]: "
labels: ["type:bug", "status:pending"]
body:
  # Summary message
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to submit a new issue. 
        Once you have submitted your new issue, the maintainer(s) will review the issue as soon as they have time available. 
        Please remember that this is a privately maintained repository, and as such issues may take longer than normal to resolve.

  # Confirm that no similar issue exists
  - type: checkboxes
    id: new-issue-confirmation
    attributes:
      label: Is there already a similar issue?
      description: Check existing issues to see if the problem you are experiencing has already been reported.
      options:
      - label: I have checked the existing issues
        required: true

  # Confirm that a title has been written
  - type: checkboxes
    id: title-confirmation
    attributes:
      label: Have you written an issue title?
      description: Write a title for the issue in the input field above. The title should describe the issue succinctly.
      options:
      - label: I have given the issue a title
        required: true      


  # Package version dropdown
  - type: dropdown
    id: package-version
    attributes:
      label: Which version of this package are you using?
      description: |
        * If you are experiencing an issue with multiple versions, select all appropriate versions
        * If you are running this package from a local build, select "LOCAL BUILD", and specify the hash of the commit which you used to build the package in the "Additional Information" textarea
        * If the package version you are using is not listed, select "OTHER", and specify correct version in the "Additional Information" textarea
      multiple: true
      options:
        - v0.0.1
        - LOCAL BUILD (specify in description)
        - OTHER (specify in description)
    validations:
      required: true

  # Node LTS version dropdown
  - type: dropdown
    id: node-version
    attributes:
      label: Which version of NodeJS are you using?
      description: |
        * If you are experiencing an issue with multiple versions, select all appropriate versions
        * If you are not running this package using NodeJS, select "NOT APPLICABLE"
        * If you are not using an LTS version of NodeJS, select "OTHER", and specify the exact version in the "Additional Information" textarea
      multiple: true
      options:
        - v18.17.1 ~ Hydrogen
        - v16.20.2 ~ Gallium
        - v14.21.3 ~ Fermium
        - v12.22.12 ~ Erbium
        - v10.24.1 ~ Dubnium
        - v8.17.0 ~ Carbon
        - v6.17.1 ~ Boron
        - v4.9.1 ~ Argon
        - NOT APPLICABLE
        - OTHER (specify in description)
    validations:
      required: true

  # Browser dropdown
  - type: dropdown
    id: browser
    attributes:
      label: Which browser are you using?
      description: |
        * If you are experiencing an issue with multiple browsers, select all appropriate browsers
        * If you are not running this package in a browser, select "NOT APPLICABLE"
        * If the browser you are using is not listed, select "OTHER", and specify the browser in the "Additional Information" textarea
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Opera
        - Edge
        - NOT APPLICABLE
        - OTHER (specify in description)
    validations:
      required: true

# thanks for reporting
# bug description
# steps to reproduce
# additonal information
# whats next?